# Generated by Django 4.0.2 on 2022-12-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_alter_user_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
        migrations.AddField(
            model_name='user',
            name='code_file',
            field=models.FileField(default=None, null=True, upload_to='code/'),
        ),
    ]
