# Generated by Django 4.0.2 on 2022-12-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_remove_user_code_user_code_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_file',
            field=models.FileField(upload_to='code/'),
        ),
    ]
